Repository C4Coin/website-public, pull requests merged in 2018-03, with the labels that each got.

#2 Feature/update node and some docs
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#3 DEV-160 setup environment
  .eslintignore
  .eslintrc.json
  .gitignore
  README.md
  base/base.config.js
  base/index.ejs
  package-lock.json
  package.json
  postcss.config.js
  web-app/index.js
  web-app/index.scss
  web-app/sections/cover/index.js
  web-app/sections/cover/index.scss
  web-app/style/_base.scss
  web-app/style/_input.scss
  web-app/style/_typeography.scss
  web-app/style/_variables.scss
  web-app/style/index.scss
  web-app/utils/squidex-api.js
  webpack.config.js
Labels: feature

#6 [Optinisation, DEV-200] added basic CircleCI and linting.
  .circleci/config.yml
  .eslintrc.js
  .eslintrc.json
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  postcss.config.js
  web-app/sections/cover/index.js
  web-app/utils/squidex-api.js
  webpack.config.js
Labels: documentation, enhancement, feature
